# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-03 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rate',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
